### ISSUE TITLE
Minify and version assets

### ISSUE THREAD

**Issue by pgrenaud** [lanmomo/lanmomo-website#120]
Minify (compress and consolidate) all CSS and JS to reduce browser payload. Also, while we're at this, add a version number in the filename, to ensure a reload on the browser side. And, don't use query string: http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/

**Comment by S0yKaf** [comment]
is this really necessary? (yet)

**Comment by jdupl** [comment]
Ça demande quand même beaucoup d'automatisation.
On a du trafic, mais pas tant. Je sais honnêtement pas si l'impact en vaut la peine.

**Comment by S0yKaf** [comment]
is it ok if we move this to M5?

**Comment by jdupl** [comment]
@pgrenaud dit moi si tu veux pour m4

**Comment by sbstp** [comment]
Si vous activez gzip sur les assets qui sont pas des images, ça devrait faire l'affaire.

**Comment by pgrenaud** [comment]
Well, minifying is not what really matter right now. I just notice that I totally omitted the important point: versioning. We need to ensure that, I one of the assets changes, especially a JS file, that it will be reloaded by the client. The proper way of doing that is with assets versioning. And, while we're at this, we could also do the assets minifying.

There is already a bunch of tools that allow you to minify, but not many to do the versioning. What I found so far (yes, more grunt tasks):
- http://stackoverflow.com/questions/21969422/grunt-plugin-for-assets-versioning
- https://github.com/yeoman/grunt-filerev
- https://github.com/yeoman/grunt-usemin

**Comment by jdupl** [comment]
Ben non pas vraiment pcq aucun cache n'est déclarée. Techniquement chaque fois que quelqu'un rehcarge le site ça fait des requêtes au serveur.

**Comment by sbstp** [comment]
Je ne pense pas que le versionning est la bonne façon de gérer la cache. Il y a déjà des mécanismes qui permettent d'invalider la cache des navigateurs lorsqu'un fichier change, notament [`If-Modified-Since`](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.25) (qui utilise le last modified time) et le [`ETAG`](http://en.wikipedia.org/wiki/HTTP_ETag) (qui utilise une somme/hash du fichier).

En production vous utiliser `nginx`, qui est un enterprise-grade `httpd`. Je serais surpris qu'il ne supporte pas au moins un des deux mécanismes. En développement vous utilisez express, et puisque c'est un environnement de développement, vous ne devriez pas configuer de cache des fichiers (et donc pas avoir de problème d'invalidation de cache).

Il y a des trucs à considérer par contre, c'est que IE cache les requêtes JSON par défaut (ce qui est une horrible idée, en passant), mais il y a des solutions. [Il s'agit de gérer manuellement la cache des requêtes JSON, côté client.](http://stackoverflow.com/questions/6115342/json-is-being-cached-incorrectly#answer-6115475)

Edit: Niveau, minification par contre, c'est toujours un plus. JS/CSS devrait être minified et gzip et JSON devrait être gzip.

**Comment by jdupl** [comment]
@SBSTP j'ai modifié nginx pour gzip le html, json, js et css.
Si la ressource n'a pas été modifiée, le serveur retourne un 304.

**Comment by sbstp** [comment]
Parfait, donc pas besoin de versionning "manuel".

**Comment by jdupl** [comment]
Ben pour le moment non, le serveur n'est pratiquement pas solicité. La bandwidth ça changerait pratiquement rien même on met des tags. Ça économiserait ~200octets à chaque 304.

Le économies ne justifient pas quant à moi l'effort à tout mettre le versionning en oeuvre.

**Comment by sbstp** [comment]
En plus si tu change souvent tu vas fill la cache du client avec plein de fichiers différents.

**Comment by pgrenaud** [comment]
> Ben non pas vraiment pcq aucun cache n'est déclarée. Techniquement chaque fois que quelqu'un rehcarge le site ça fait des requêtes au serveur.

Cool. Dans de cas, on va simplement avoir besoin de rouler `grunt-contrib-concat` sur les assets javascript et css. On va améliorer de beaucoup la vitesse de chargement avec ça. [Explication](http://stackoverflow.com/a/14101906).
