### ISSUE TITLE
First Name and Last Name formating ? 

### ISSUE THREAD

**Issue by RickyNotaro** [lanmomo/lanmomo-website#123]
Some users don't have the first letter of their first and last name capitalized on the /users page. Should we auto-capitalize them?

http://i.imgur.com/tW5aAP9.png

**Comment by S0yKaf** [comment]
good point

**Comment by fxleblanc** [comment]
Thanks @RickyNotaro. Good observation. In my opinion, both firstname and lastname should be capitalized. @jdupl, we could finish this in m4 since it doesn't affect the backend code. Plus, it's an easy fix.

https://docs.angularjs.org/api/ng/filter/uppercase

@Kiniamaro do you want it or do you want me to do it?

**Comment by jdupl** [comment]
oui @petit-prince c'est dans m4
